# Generated by Django 5.0.1 on 2024-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otprequest_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone number')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
