# Generated by Django 5.0.1 on 2024-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sentsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='verified_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
