# Generated by Django 5.0.1 on 2024-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='reasons',
            field=models.CharField(choices=[('OTP', 'ارسال کد تایید')], default='OTP', max_length=50, verbose_name='reason'),
            preserve_default=False,
        ),
    ]
