# Generated by Django 5.0.1 on 2024-02-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_deleted_otprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_otp_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
