# Generated by Django 5.0.1 on 2024-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sentsms_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentsms',
            name='reasons',
        ),
        migrations.AddField(
            model_name='sentsms',
            name='reason',
            field=models.CharField(choices=[('OTP', 'send otp code')], default='OTP', max_length=50, verbose_name='reason'),
            preserve_default=False,
        ),
    ]
