# Generated by Django 5.0.1 on 2024-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otprequest_options_alter_sentsms_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='monthly_price',
            new_name='monthly_payment',
        ),
    ]
