# Generated by Django 5.0.1 on 2024-03-28 17:17

import apps.utils.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_monthly_price_user_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, max_length=500, null=True, quality=99, scale=None, size=[200, 200], upload_to='avatar', validators=[apps.utils.validators.ValidateFileExtension(['.png', '.jpg', '.jpeg'])], verbose_name='avatar'),
        ),
    ]
