version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env
  django:
    build:
      context: .
    volumes:
      - ./:/app
      - media:/app/media/
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


volumes:
  data:
  media: