# Generated by Django 5.0.1 on 2024-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_is_valid_payment_other_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='other_info',
            field=models.JSONField(default=dict),
        ),
    ]
