# Generated by Django 5.0.1 on 2024-03-28 17:17

import apps.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_other_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='', validators=[apps.utils.validators.ValidateFileExtension(['.png', '.jpg', '.jpeg', '.pdf'])], verbose_name='attachment')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_attachment', to='payment.paymentrequest', verbose_name='payment request')),
            ],
        ),
    ]
