# Generated by Django 5.0.1 on 2024-03-29 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentrequestattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequestattachment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='paymentrequestattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequestattachment',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='paymentrequestattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
